name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.GENMATCHA_DEPLOY_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            echo "Listing directory contents:"
            ls -la
            echo "Changing to deployment directory..."
            cd /var/www/newmooncloud
            echo "Current directory: $(pwd)"
            echo "Listing directory contents:"
            ls -la
            echo "Pulling latest changes..."
            git pull origin main
            echo "Installing dependencies..."
            npm install
            echo "Building site..."
            npm run build
            echo "Restarting Apache..."
            sudo systemctl restart apache2
            echo "Deployment completed successfully!" 